site_name: Yomitan
site_url: https://yomitan.wiki/
site_description: Japanese pop-up dictionary browser extension
site_author: Yomitan Authors
repo_url: https://github.com/themoeway/yomitan
repo_name: Yomitan
nav:
  - Home:
    - Introduction: 'index.md'
    - Changes: 'change-log.md'
    - Contributing: 'contributing.md'
  - Getting started: 'getting-started/index.md'
  - Dictionaries:
    - Using dictionaries: 'dictionaries/index.md'
    - Making yomitan dictionaries: 'dictionaries/making-yomitan-dictionaries.md'
  - Anki:
    - Anki integration: 'anki/index.md'
    - Templates: 'anki/templates.md'
  - Advanced Features:
    - Keyboard shortcuts: 'advanced/keyboard-shortcuts.md'
    - Advanced options, including MeCab: 'advanced/advanced-options.md'
    - Adding custom audio sources: 'advanced/audio.md'
  - Other:
    - FAQ: 'other/faq.md'
    - Browser permissions: 'other/permissions.md'
    - Supported languages: 'other/supported-languages.md'
    - Migrating from Yomichan (legacy): 'other/yomichan-migration.md'
  - Contributing:
    - Contributing: 'contributing/index.md'
    - Language Features: 'contributing/language-features.md'
    - NPM Scripts: 'contributing/npm-scripts.md'
theme:
  name: material
  favicon: assets/icon/yomitan-icon64.png
  logo: assets/icon/yomitan-icon128.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: purple
      accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: deep purple
      accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/themoeway/yomitan
    - icon: fontawesome/brands/discord
      link: https://discord.gg/tmw
  homepage: https://yomitan.wiki/
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized
  - search:
      lang:
        - en
        - ja

copyright: Copyright &copy; 2024 Yomitan Authors